version: '2.3.3'
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  app1:
    build: /home/user/express_app/
    volumes:
      - .:/home/user/express_app/App
    ports:
      - "8080:3000"
  app2:
    build: /home/user/devop2/
    volumes:
      - .:/home/user/devop2/App2
    ports:
      - "8081:3001"
    
